server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/energytrack?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 314221
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost        # Redis 服务器地址
    port: 6379            # Redis 端口，默认 6379
    password:             # Redis 密码（如果有的话）
    database: 0           # Redis 数据库索引（0-15，默认 0）
    timeout: 5000ms       # 连接超时时间
    lettuce:              # Lettuce 客户端配置（可选）
      pool:
        max-active: 8     # 连接池最大连接数
        max-idle: 8       # 连接池最大空闲连接数
        min-idle: 0       # 连接池最小空闲连接数
        max-wait: -1ms    # 连接池最大等待时间（-1 表示无限制）

  cache:
    type: redis

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    cn.edu.cqrk.energytrack.filter.JwtAuthenticationFilter: debug
    cn.edu.cqrk.energytrack.service.impl: debug



mybatis-plus:
  configuration:
    # 设置 MyBatis 的日志实现类，这里使用的是标准输出日志实现类（org.apache.ibatis.logging.stdout.StdOutImpl）
    # 用于在控制台打印 SQL 日志，方便调试和查看 SQL 执行情况
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    # 当查询结果为空时，是否返回一个空的实例对象
    # 如果设置为 true，当查询没有匹配的记录时，MyBatis 会返回一个空实例，而不是 null
    return-instance-for-empty-row: true

    # 是否将数据库的下划线命名方式映射为 Java 类的驼峰命名方式
    # 设置为 true 时，MyBatis-Plus 会将数据库中如 "sysuser_name" 自动映射为 Java 类中的 "sysUserName"
    map-underscore-to-camel-case: true

  # 指定实体类所在的包路径，用于 MyBatis-Plus 自动扫描这些类并进行映射
  # 在该路径下的实体类将自动被 MyBatis-Plus 作为数据库表的映射类
  type-aliases-package: cn.edu.cqrk.energytrack.entity.pojo

jwt:
  secret: "d2d4d6f8e0a2c4e6g8i0k2m4o6q8s0u2w4y6"
  expiration: 86400 # token有效期(秒) 默认24小时